apiVersion: v1
kind: Secret
metadata:
  name: lulufriends-secret
  namespace: default
type: Opaque
stringData:
  # Spring DataSource 설정 (우선순위 높임)
  SPRING_DATASOURCE_URL: "jdbc:mysql://db-34ik2v.vpc-cdb.ntruss.com/lulufriends?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  SPRING_DATASOURCE_USERNAME: "lulufriends"
  SPRING_DATASOURCE_PASSWORD: "lulu123!@#"
  
  # 기존 환경변수도 유지
  DB_URL: "jdbc:mysql://db-34ik2v.vpc-cdb.ntruss.com/lulufriends?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
  DB_USERNAME: "lulufriends"
  DB_PASSWORD: "lulu123!@#"
  
  # 기타 필수 환경변수
  JWT_SECRET: "L7u9Kx3P8nQ2mB5cF1rE6wT0yH4vJ9sA"
  baseUrl: "http://default-lulufriends-back-95384-105469737-02d0b2769cfe.kr.lb.naverncp.com"
